
baseURL: http://rusticus.io/
languageCode: en-us
title: rusticus.io

theme: rusticus

Paginate: 5

taxonomies:
  tag: tags

outputs:
  home:
  - HTML
  page:
  - HTML
  - RSS

params:

  title: Rust Community Stuttgart

  dateformat: "2006-01-02"
